/**
 * Google Material Symbols — the whole catalogue at fonts.google.com/icons.
 *
 * Two facts shape how this works:
 *
 *  - Google's icon *metadata* endpoint (fonts.google.com/metadata/icons) sends
 *    no CORS header, so a browser cannot read it. The names are bundled
 *    instead, generated by scripts/build-material-symbols.mjs from Google's
 *    own published index, and the list is loaded on demand so 74 KB of names
 *    is not in the initial bundle.
 *  - The SVG endpoint on fonts.gstatic.com *does* answer
 *    `access-control-allow-origin: *`, so the geometry of the one icon a
 *    person picks is fetched directly — no proxy, no server. That host is
 *    already in the desktop shell's CSP for web fonts.
 *
 * A fetched symbol is stored on the layer as raw path data, so a project that
 * travels to another machine, or into the headless exporter, renders without
 * needing the network again.
 */

const SVG_HOST = 'https://fonts.gstatic.com/s/i/short-term/release'

/** The three shapes Google draws every symbol in. */
export const SYMBOL_STYLES = ['outlined', 'rounded', 'sharp'] as const
export type SymbolStyle = (typeof SYMBOL_STYLES)[number]

/** The weights the endpoint serves. 400 is the default and has no segment. */
export const SYMBOL_WEIGHTS = [100, 200, 300, 400, 500, 600, 700] as const
export type SymbolWeight = (typeof SYMBOL_WEIGHTS)[number]

export interface SymbolVariant {
  style: SymbolStyle
  /** Filled shapes rather than outlines — Google's "Fill" axis. */
  filled: boolean
  weight: SymbolWeight
}

export const DEFAULT_VARIANT: SymbolVariant = { style: 'outlined', filled: false, weight: 400 }

/**
 * The URL segment naming a variant.
 *
 * Weight 400 unfilled is `default`; everything else composes as
 * `wght<n>` then `fill1`, which is the order the endpoint expects.
 */
export function variantSegment({ filled, weight }: SymbolVariant): string {
  const parts: string[] = []
  if (weight !== 400) parts.push(`wght${weight}`)
  if (filled) parts.push('fill1')
  return parts.length ? parts.join('') : 'default'
}

export function symbolUrl(name: string, variant: SymbolVariant = DEFAULT_VARIANT): string {
  return `${SVG_HOST}/materialsymbols${variant.style}/${encodeURIComponent(name)}/${variantSegment(variant)}/24px.svg`
}

export interface FetchedSymbol {
  /** Raw path data, in the symbol's own coordinate space. */
  d: string
  /** The symbol's viewBox — Material uses `0 -960 960 960`, not `0 0 24 24`. */
  viewBox: string
  /**
   * Whether the geometry is a solid shape.
   *
   * True for a filled variant, but also for an unfilled one: Material Symbols
   * are drawn as filled outlines, not as strokes, so the renderer must paint
   * them with `fill` either way.
   */
  filled: true
}

/** Loaded on demand — 4,400 names have no business in the initial bundle. */
let namesPromise: Promise<readonly string[]> | null = null

export function loadSymbolNames(): Promise<readonly string[]> {
  namesPromise ??= import('@/assets/icons/materialSymbolNames').then((m) => m.MATERIAL_SYMBOL_NAMES)
  return namesPromise
}

/**
 * Underscores read as spaces, so "rocket launch" finds `rocket_launch`.
 *
 * Every term must match, and a term matching the start of a word ranks above
 * one matching the middle: searching "car" should offer `car` and `car_rental`
 * before `scorecard`.
 */
export function searchMaterialSymbols(query: string, names: readonly string[], limit = 400): string[] {
  const terms = query.toLowerCase().split(/[\s_-]+/).filter(Boolean)
  if (terms.length === 0) return names.slice(0, limit)

  const scored: { name: string; score: number }[] = []
  for (const name of names) {
    const haystack = name.replace(/_/g, ' ')
    let score = 0
    let matchedAll = true
    for (const term of terms) {
      const at = haystack.indexOf(term)
      if (at < 0) { matchedAll = false; break }
      // Exact, then word-initial, then anywhere.
      if (haystack === term) score += 100
      else if (at === 0 || haystack[at - 1] === ' ') score += 10
      else score += 1
    }
    if (matchedAll) scored.push({ name, score })
  }

  scored.sort((a, b) => b.score - a.score || a.name.length - b.name.length || a.name.localeCompare(b.name))
  return scored.slice(0, limit).map((entry) => entry.name)
}

/** Parsed symbols, keyed by name *and* variant, so re-picking never refetches. */
const cache = new Map<string, FetchedSymbol>()

/**
 * Pull one symbol's geometry.
 *
 * Parsed with DOMParser rather than a regex: the response is a real SVG
 * document, and reading `getAttribute` off it is both simpler and safe against
 * attribute-order changes. Nothing from the response is ever inserted into the
 * page — only the `d` and `viewBox` strings are kept.
 */
export async function fetchMaterialSymbol(
  name: string,
  variant: SymbolVariant = DEFAULT_VARIANT,
): Promise<FetchedSymbol> {
  const key = `${variant.style}/${variantSegment(variant)}/${name}`
  const cached = cache.get(key)
  if (cached) return cached

  const response = await fetch(symbolUrl(name, variant))
  if (!response.ok) throw new Error(`Material symbol "${name}" returned ${response.status}.`)
  const markup = await response.text()

  const document_ = new DOMParser().parseFromString(markup, 'image/svg+xml')
  const svg = document_.querySelector('svg')
  const paths = [...document_.querySelectorAll('path')]
  if (!svg || paths.length === 0) throw new Error(`Material symbol "${name}" had no path data.`)

  // Several <path> elements concatenate into one `d` as independent subpaths,
  // which keeps a fetched icon to a single Konva node like a bundled one.
  const d = paths.map((path) => path.getAttribute('d') ?? '').filter(Boolean).join(' ')
  if (!d) throw new Error(`Material symbol "${name}" had no path data.`)

  const symbol: FetchedSymbol = {
    d,
    viewBox: svg.getAttribute('viewBox') ?? '0 -960 960 960',
    filled: true,
  }
  cache.set(key, symbol)
  return symbol
}

/** `viewBox` as four numbers, falling back to Material's own box. */
export function parseViewBox(viewBox: string | undefined): [number, number, number, number] {
  const parts = (viewBox ?? '').split(/[\s,]+/).map(Number)
  if (parts.length === 4 && parts.every((value) => Number.isFinite(value)) && parts[2] > 0 && parts[3] > 0) {
    return [parts[0], parts[1], parts[2], parts[3]]
  }
  return [0, 0, 24, 24]
}
